domain: bigbang.dev

# Uncomment the following settings if using the AWS RKE2 terraform setup
# istio:
#   ingressGateways:
#     public-ingressgateway:
#       type: "NodePort"
#       nodePortBase: 30000

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

logging:
  git:
    repo: https://repo1.dso.mil/big-bang/product/packages/elasticsearch-kibana.git
    tag: "1.1.0-bb.1"
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 256Mi
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
      data:
        count: 1
        persistence:
          size: 256Mi
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
    kibana:
      count: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi

monitoring:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/monitoring.git
    tag: "43.1.2-bb.4"
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

fluentbit:
  git:
    repo: https://repo1.dso.mil/big-bang/product/packages/fluentbit.git
    tag: "0.25.0-bb.0"
  values:
    securityContext:
      privileged: true

gatekeeper:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/policy.git
    tag: "3.11.0-bb.2"
  values:
    replicas: 1
    controllerManager:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    audit:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi

kyverno:
  git:
    repo: https://repo1.dso.mil/big-bang/product/packages/kyverno.git
    tag: "2.6.5-bb.3"
  values:
    replicaCount: 1

twistlock:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/security-tools/twistlock.git
    tag: "0.12.0-bb.0"
  enabled: false
  values:
    console:
      persistence:
        size: 256Mi
